
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SkyDuDe
 */
public class AppInscricoes extends javax.swing.JFrame {

    static ArrayList<Formandos> lista = new ArrayList<>();

///global variables////
    static int idFormando = 1;

    /**
     * Creates new form AppInscricoes
     */
    public AppInscricoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jfRegistarFormando = new javax.swing.JButton();
        jfCarregar = new javax.swing.JButton();
        jfEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfIDaluno = new javax.swing.JTextField();
        jfNome = new javax.swing.JTextField();
        jfIdade = new javax.swing.JTextField();
        jfAltura = new javax.swing.JTextField();
        jfPais = new javax.swing.JTextField();
        jfMasc = new javax.swing.JRadioButton();
        jfFemi = new javax.swing.JRadioButton();
        jfModificarF = new javax.swing.JButton();
        jfGuardar = new javax.swing.JButton();
        jfRestaura = new javax.swing.JButton();
        jfcarregar = new javax.swing.JTextField();
        jfClean = new javax.swing.JButton();
        jfAtualizarFormando = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jfID = new javax.swing.JSpinner();
        jfListarF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jfDisp = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDispL = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfRegistarFormando.setText("Registar Formando");
        jfRegistarFormando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jfRegistarFormandoMouseClicked(evt);
            }
        });
        jfRegistarFormando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfRegistarFormandoActionPerformed(evt);
            }
        });

        jfCarregar.setText("Carregar Formando");
        jfCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCarregarActionPerformed(evt);
            }
        });

        jfEliminar.setText("Eliminar Formando");
        jfEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Formando");

        jLabel2.setText("Nome");

        jLabel3.setText("País");

        jLabel4.setText("Idade");

        jLabel5.setText("Altura");

        jLabel6.setText("Sexo");

        jfIDaluno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jfIDaluno.setEnabled(false);

        jfSexo.add(jfMasc);
        jfMasc.setText("Masculino");

        jfSexo.add(jfFemi);
        jfFemi.setText("Feminino");

        jfModificarF.setText("Modificar Formando");
        jfModificarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfModificarFActionPerformed(evt);
            }
        });

        jfGuardar.setText("Guardar  Listagem");
        jfGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfGuardarActionPerformed(evt);
            }
        });

        jfRestaura.setText("Carregar Listagem");
        jfRestaura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfRestauraActionPerformed(evt);
            }
        });

        jfClean.setText("Limpar");
        jfClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCleanActionPerformed(evt);
            }
        });

        jfAtualizarFormando.setText("Atualizar Formando");
        jfAtualizarFormando.setEnabled(false);
        jfAtualizarFormando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfAtualizarFormandoActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome do Ficheiro");

        jfID.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jfListarF.setText("Listar Formandos");
        jfListarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfListarFActionPerformed(evt);
            }
        });

        jfDisp.setColumns(20);
        jfDisp.setLineWrap(true);
        jfDisp.setRows(5);
        jfDisp.setAutoscrolls(false);
        jfDisp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(jfDisp);

        jDispL.setColumns(20);
        jDispL.setRows(5);
        jScrollPane1.setViewportView(jDispL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jfIdade)
                                .addComponent(jfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(115, 115, 115))
                                    .addComponent(jfcarregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jfMasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jfFemi))
                                    .addComponent(jfPais, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfAtualizarFormando)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jfRegistarFormando, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jfListarF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)
                                        .addComponent(jfGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jfRestaura, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jfCarregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfModificarF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jfClean))
                            .addComponent(jfIDaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfCarregar)
                    .addComponent(jfEliminar)
                    .addComponent(jfModificarF)
                    .addComponent(jfClean)
                    .addComponent(jfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(jfIDaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34))
                                    .addComponent(jfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jfMasc)
                                    .addComponent(jfFemi))
                                .addGap(18, 18, 18)
                                .addComponent(jfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jfAtualizarFormando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jfRegistarFormando)
                                    .addComponent(jfListarF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jfGuardar)
                                    .addComponent(jfRestaura))
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jfcarregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Formandos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cursos", jPanel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Disciplinas", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inscrever Formandos", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Adicionar Disciplina a um Curso", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfRegistarFormandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfRegistarFormandoActionPerformed

        Formandos formandos = new Formandos();
        formandos.setId(idFormando++);
        jfIDaluno.setText(String.valueOf(idFormando));
        formandos.setNome(jfNome.getText());
        formandos.setIdade(Integer.parseInt(jfIdade.getText()));
        formandos.setAltura(Integer.parseInt(jfAltura.getText()));
        if (jfMasc.isSelected()) {
            formandos.setSexo(true);
        } else {
            formandos.setSexo(false);
        }
        formandos.setPais(jfPais.getText());

        lista.add(formandos);
    }//GEN-LAST:event_jfRegistarFormandoActionPerformed

    private void jfGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfGuardarActionPerformed
        try {
            FileOutputStream fileOutputStream = new FileOutputStream(jfcarregar.getText());
            try ( ObjectOutputStream objectOutputStream = new ObjectOutputStream(fileOutputStream)) {
                objectOutputStream.writeObject(lista);
                objectOutputStream.flush();
            } catch (IOException ex) {
                Logger.getLogger(AppInscricoes.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(AppInscricoes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jfGuardarActionPerformed

    private void jfRestauraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfRestauraActionPerformed
        //JFileChooser chooser = new JFileChooser();
        //chooser.showOpenDialog(null);
        //File f = chooser.getSelectedFile();
        //String filename = f.
        //disp.setText(filename);
        FileInputStream fileInputStream = null;

        try {
            fileInputStream = new FileInputStream(jfcarregar.getText());
            try ( ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream)) {
                lista = (ArrayList<Formandos>) objectInputStream.readObject();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(AppInscricoes.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (int z = 0; z < lista.size(); z++) {
                jfIDaluno.setText(String.valueOf((lista.get(z).getId())));
                jfNome.setText(String.valueOf((lista.get(z).getNome())));
                jfIdade.setText(String.valueOf((lista.get(z).getIdade())));
                jfAltura.setText(String.valueOf((lista.get(z).getAltura())));
                jfPais.setText(String.valueOf((lista.get(z).getPais())));
                jfDisp.setText(String.valueOf(lista.get(z)));
                if (lista.get(z).isSexo() == true) {
                    jfMasc.setSelected(true);

                } else {
                    jfFemi.setSelected(true);
                }

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AppInscricoes.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(AppInscricoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jfRestauraActionPerformed

    private void jfCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCleanActionPerformed
        jfIDaluno.setText("");
        jfNome.setText("");
        jfIdade.setText("");
        jfAltura.setText("");
        jfPais.setText("");
        jfSexo.clearSelection();
        jfDisp.setText("");


    }//GEN-LAST:event_jfCleanActionPerformed

    private void jfCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCarregarActionPerformed
        //for (int x = 1; x < lista.size(); x++) {

        jfIDaluno.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getId())));
        jfNome.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getNome())));
        jfIdade.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getIdade())));
        jfAltura.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getAltura())));
        jfPais.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getPais())));
        jfDisp.setText(String.valueOf(lista.get((int) jfID.getValue() - 1)));
        if (lista.get((int) jfID.getValue() - 1).isSexo() == true) {
            jfMasc.setSelected(true);

        } else {
            jfFemi.setSelected(true);
        }
        //}
    }//GEN-LAST:event_jfCarregarActionPerformed

    private void jfEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfEliminarActionPerformed
        Formandos formandos = new Formandos();
        lista.remove((int) jfID.getValue() - 1);
        idFormando = 2;
        int j = lista.size();
        for (int x = 2; x < j + 1; x++) {
            formandos = lista.get(x - 1);
            formandos.setId(idFormando++);
        }
    }//GEN-LAST:event_jfEliminarActionPerformed

    private void jfAtualizarFormandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfAtualizarFormandoActionPerformed
        lista.get((int) jfID.getValue() - 1).setNome(jfNome.getText());
        lista.get((int) jfID.getValue() - 1).setIdade(Integer.parseInt(jfIdade.getText()));
        lista.get((int) jfID.getValue() - 1).setAltura(Integer.parseInt(jfAltura.getText()));
        lista.get((int) jfID.getValue() - 1).setPais(jfPais.getText());

        if (jfMasc.isSelected()) {
            lista.get((int) jfID.getValue() - 1).setSexo(true);

        } else {
            lista.get((int) jfID.getValue() - 1).setSexo(false);
        }
        jfAtualizarFormando.setEnabled(false);
    }//GEN-LAST:event_jfAtualizarFormandoActionPerformed

    private void jfRegistarFormandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfRegistarFormandoMouseClicked
        jfNome.setText("");
        jfIdade.setText("");
        jfAltura.setText("");
        jfPais.setText("");
        jfSexo.clearSelection();
    }//GEN-LAST:event_jfRegistarFormandoMouseClicked

    private void jfModificarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfModificarFActionPerformed
        jfAtualizarFormando.setEnabled(true);
        jfIDaluno.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getId())));
        jfNome.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getNome())));
        jfIdade.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getIdade())));
        jfAltura.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getAltura())));
        jfPais.setText(String.valueOf((lista.get((int) jfID.getValue() - 1).getPais())));
        jfDisp.setText(String.valueOf(lista.get((int) jfID.getValue() - 1)));
        if (lista.get((int) jfID.getValue() - 1).isSexo() == true) {
            jfMasc.setSelected(true);

        } else {
            jfFemi.setSelected(true);
        }
        //jfNome.setText("");
        //jfIdade.setText("");
        //jfAltura.setText("");
        //jfPais.setText("");
        //jfSexo.clearSelection();
    }//GEN-LAST:event_jfModificarFActionPerformed

    private void jfListarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfListarFActionPerformed
    	for (Formandos f : lista)
    	{ 
            System.out.println(f.toString());
            jDispL.append(f.toString()+ "\n");
                //jDispL.setText(String.valueOf(lista.get()) + "\n");
    		//System.out.println(lista.get(i)); 
    	} 
    }//GEN-LAST:event_jfListarFActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppInscricoes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppInscricoes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppInscricoes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppInscricoes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppInscricoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jDispL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jfAltura;
    private javax.swing.JButton jfAtualizarFormando;
    private javax.swing.JButton jfCarregar;
    private javax.swing.JButton jfClean;
    private javax.swing.JTextArea jfDisp;
    private javax.swing.JButton jfEliminar;
    private javax.swing.JRadioButton jfFemi;
    private javax.swing.JButton jfGuardar;
    private javax.swing.JSpinner jfID;
    private javax.swing.JTextField jfIDaluno;
    private javax.swing.JTextField jfIdade;
    private javax.swing.JButton jfListarF;
    private javax.swing.JRadioButton jfMasc;
    private javax.swing.JButton jfModificarF;
    private javax.swing.JTextField jfNome;
    private javax.swing.JTextField jfPais;
    private javax.swing.JButton jfRegistarFormando;
    private javax.swing.JButton jfRestaura;
    private javax.swing.ButtonGroup jfSexo;
    private javax.swing.JTextField jfcarregar;
    // End of variables declaration//GEN-END:variables
}
